### ISSUE TITLE
Note on installing

### ISSUE THREAD

**Issue by cholcombe973** [tov/libffi-rs#1]
Just a quick note for ubuntu 14.04.  I had to install texinfo to get cargo to compile libffi-sys.  I didn't see that in the .travis.yaml so I was a little confused how you got it working.

**Comment by tov** [comment]
Huh, I'm not sure. Does Travis CI not install texinfo by default?

Is there something in the package I should change? What are you using it
for?

Jesse

On Thu, Dec 8, 2016 at 6:10 PM Chris Holcombe <notifications@github.com>
wrote:

Just a quick note for ubuntu 14.04. I had to install texinfo to get cargo
to compile libffi-sys. I didn't see that in the .travis.yaml so I was a
little confused how you got it working.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/tov/libffi-rs/issues/1>, or mute the thread

**Comment by cholcombe973** [comment]
I'm potentially going to use libffi for callbacks from Ceph and Gluster.
I'm hoping it'll fit the bill. I started with Gluster today because i think
the callback mechanism is more straightforward. See:
https://github.com/gluster/Gfapi-sys/blob/master/src/glfs.rs#L9. It's used
in all the async calls. I'm thinking of having the caller pass a closure
for callback processing. The harder one is Ceph:
https://github.com/ceph/ceph-rust/blob/master/src/rados.rs#L165.

The default Travis environment uses ubuntu 12.04. I'm guessing the default
packages installed changed in 14.04. Either that or it's because I'm using
xubuntu 14.04.
